<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>throwError</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rxjs/7.4.0/rxjs.umd.js"></script>
    <script>
        const { throwError } = rxjs;
        throwError("Message d'erreur")
            .subscribe(
                next => console.log(new Date(Date.now()).toJSON() , 'next:', next),
                err => console.log(new Date(Date.now()).toJSON() , 'error:', err),
                () => console.log(new Date(Date.now()).toJSON() , 'complete'),
            );

        throwError(new Error("Message d'erreur"))
            .subscribe(
                next => console.log(new Date(Date.now()).toJSON() , 'next:', next),
                err => console.log(new Date(Date.now()).toJSON() , 'error:', err.message),
                () => console.log(new Date(Date.now()).toJSON() , 'complete'),
            );
    </script>
</head>
<body>

</body>
</html>
